### ISSUE TITLE
ice36-devel is missing

### ISSUE THREAD

**Issue by joshmoore** [ome/omero-install#112]
It's slightly confusing that ice36 installs devel requirements (like slice2py) but ice35 doesn't. Probably worth unifying. (Note: this came from trying to change ice36 in devspace to ice35 and then having slice2java not on the path)

**Comment by atarkowska** [comment]
https://github.com/ome/omero-install/blob/develop/linux/step01_centos7_ice_deps.sh

**Comment by manics** [comment]
Does ice36 need the devel packages at all?

**Comment by joshmoore** [comment]
@manics : quite possibly not, and it might be just that disparity that leads to confusion.

**Comment by joshmoore** [comment]
@jburel: worth reviewing for 5.3?

**Comment by jburel** [comment]
will try to see if I can have something today otherwise will look at it in 5.3.1

**Comment by jburel** [comment]
unlikely now, I had to work on homebrew

**Comment by jburel** [comment]
I came back to that issue today
It is not possible to install the python binding i.e. ``pip install "zeroc-ice>3.5,<3.7"``
if ``openssl-devel`` and  ``bzip2-devel`` are not installed
``expat-devel`` is not necessary. This can be removed.

**Comment by jburel** [comment]
https://github.com/ome/omero-install/pull/175
