### ISSUE TITLE
ubuntu 16.04 ice version chaos

### ISSUE THREAD

**Issue by heidricha** [ome/omero-install#148]
Very nice install environment, thanks a lot!

Still I have got a few problems:

- the followings must be installed by hand before running the script: libssl-dev libghc-bzlib-dev 
- ice 3.6 must be installed with pip before running the script as well: pip install zeroc-ice. the script seems to handle the versions, but it doesn't
- server cannot start with ice 3.6.3, system complains, that not compatible with 3.5.1 (not installed at all) ERROR: "icegridnode version is not compatible with 3.6.3: 3.5.1"

+ OMERO.server/bin/omero config set omero.data.dir /OMERO
Traceback (most recent call last):
  File "OMERO.server/bin/omero", line 97, in <module>
    import omero.cli
  File "/home/omero/OMERO.server/lib/python/omero/__init__.py", line 43, in <module>
    raise Exception(msg)
Exception: 

        ERROR: Ice version mismatch!

        Your OMERO code has been compiled using Ice version 3.6.3
        but you seem to have Ice version 3.5.1 installed. If you need
        help understanding this issue, please send this error message
        to the OME community:

        http://www.openmicroscopy.org/site/community

        Debugging Info:
        --------------
        VERSION=5.2.7-ice36-b40
        PYTHONPATH=/home/omero/OMERO.server/lib/python:/home/omero/OMERO.server/var/lib:/home/omero/OMERO.server-5.2.7-ice36-b40/bin:/usr/lib/python2.7:/usr/lib/python2.7/plat-x86_64-linux-gnu:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload:/usr/local/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages/PILcompat:/home/omero/OMERO.server/lib/fallback

I plan to run a container for omero, my current Dockerfile is:

FROM ubuntu:xenial

RUN apt-get update && apt-get -y upgrade

RUN apt install -y git libssl-dev python-pip libghc-bzlib-dev
RUN pip install --upgrade pip
RUN pip install "zeroc-ice==3.6.3"
RUN git clone https://github.com/ome/omero-install.git
WORKDIR omero-install/linux
RUN bash install_ubuntu1604_nginx.sh

CMD service postgresql start && \
    service omero start && \
    service omero-web start && \
    while true;do sleep 120;done

**Comment by manics** [comment]
Hi @heidricha 

What command(s) did you run? In general this repository is used to auto-generate our installation docs so may correspond to our development rather than released version. The docs for our latest release (5.2.X) are at http://www.openmicroscopy.org/site/support/omero5.2/sysadmins/unix/index.html

**Comment by heidricha** [comment]
Hi!

The commands I ran are in the Dockerfile.

I run "bash install_ubuntu1604_nginx.sh" for installation.
Then "service omero start" - does nothing. If I try to start with "omero admin", I got the message about ice versions.

Anyway, I have found a problem with the installer:
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys EEA14886 # doesn't work.
I must use hkp://keyserver.ubuntu.com:80 instead. It should be related to our internal networking environment. 

Just testing...
also I try to override the ICEVER variable to force ice36 to be used.

Image creation went fine, needs more investigation to tell any more.

**Comment by jburel** [comment]
The dependency ``libghc-bzlib-dev`` is not currently installed in, the others one are.
https://github.com/ome/omero-install/blob/develop/linux/step01_ubuntu_ice_deps.sh
I will check on our side too

Do you require haskell bindings to make it work?

**Comment by heidricha** [comment]
I have modified a few things:

ENV DEBIAN_FRONTEND=noninteractive \
    ICEVER=ice36 \
    WEBSESSION=false

RUN apt-get update && apt-get -y install software-properties-common git
RUN apt-get update && apt-get -y install db5.3-util
RUN apt-get update && apt-get -y install libssl-dev libbz2-dev libmcpp-dev libdb++-dev libdb-dev
RUN apt-key adv --keyserver hkp://pgp.mit.edu:80 --recv-keys 5E6DA83306132997 
RUN apt-add-repository "deb http://zeroc.com/download/apt/ubuntu`lsb_release -rs` stable main"
RUN apt-get update && apt-get -y install zeroc-ice-all-runtime zeroc-ice-all-dev
RUN apt-get update && apt-get -y install python-pip
RUN pip install --upgrade pip
RUN pip install "zeroc-ice>3.5,<3.7"

RUN git clone https://github.com/ome/omero-install.git
WORKDIR omero-install/linux
RUN sed -e 's%\(keyserver.ubuntu.com\)%hkp://\1:80%' -i ./step01_debian8_java_deps.sh
RUN sed -e 's%\(keyserver.ubuntu.com\)%hkp://\1:80%' -i ./step01_ubuntu_ice_deps.sh

RUN bash install_ubuntu1604_nginx.sh

without the "sed" commands, the repository keys cannot be downloaded. It is very probably caused by our network infrastructure, but should not harm anyone else, so I recommend to use port 80 in the key URLs by default.

versions are kinda cleared, I am goning to close this issue, but will open another, since cannot start the server:

omero@255207fcf2dc:~/OMERO.server$ bin/omero admin start
No descriptor given. Using etc/grid/default.xml
Waiting on startup. Use CTRL-C to exit
.............................
Failed to startup some components after 300 seconds
Calling "stop" on remaining components
Waiting on shutdown. Use CTRL-C to exit
......omero@255207fcf2dc:~/OMERO.server
