### ISSUE TITLE
TCP port configuration

### ISSUE THREAD

**Issue by heidricha** [ome/omero-install#151]
I feel like getting closer to a working Dockerized server, but still don't know, which port should be used for what.

By default:
4061: icegridregistry
4063: glacier2router
5432: postgres
somehighports: icegridnode

now omero can be started
omero-web and nginx also can be started

"omero login" complains "no server on 4064". really. what should be listening there?

omero> admin diagnostics 

================================================================================
OMERO Diagnostics 5.2.7-ice36-b40
================================================================================
        
Commands:   java -version                  1.8.0     (/usr/bin/java)
Commands:   python -V                      2.7.12    (/usr/bin/python)
Commands:   icegridnode --version          3.6.3     (/usr/bin/icegridnode)
Commands:   icegridadmin --version         3.6.3     (/usr/bin/icegridadmin)
Commands:   psql --version                 9.4.11    (/usr/bin/psql)

Server:     icegridnode                    not started

Log dir:    /home/omero/OMERO.server-5.2.7-ice36-b40/var/log exists
Log files:  Blitz-0.log                    n/a
Log files:  DropBox.log                    n/a
Log files:  FileServer.log                 n/a
Log files:  Indexer-0.log                  n/a
Log files:  MonitorServer.log              n/a
Log files:  OMEROweb.lock                  0.0 KB       
Log files:  OMEROweb.log                   0.0 KB        errors=0    warnings=1   
Log files:  OMEROweb_brokenrequest.lock    0.0 KB       
Log files:  OMEROweb_brokenrequest.log     0.0 KB       
Log files:  Processor-0.log                n/a
Log files:  Tables-0.log                   n/a
Log files:  TestDropBox.log                n/a
Log files:  master.err                     0.0 KB        errors=1    warnings=0   
Log files:  master.out                     0.0 KB       
Log files:  Total size                     0.00 MB

Error while parsing logs

Environment:OMERO_HOME=(unset)             
Environment:OMERO_NODE=(unset)             
Environment:OMERO_MASTER=(unset)           
Environment:OMERO_USERDIR=(unset)          
Environment:OMERO_TMPDIR=(unset)           
Environment:PATH=/home/omero/bin:/home/omero/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games 
Environment:PYTHONPATH=(unset)             
Environment:ICE_HOME=(unset)               
Environment:LD_LIBRARY_PATH=(unset)        
Environment:DYLD_LIBRARY_PATH=(unset)      

Cannot list deployed applications.
OMERO data dir:'/OMERO'                       Exists? True	Is writable? True
OMERO temp dir:'/home/omero/omero/tmp'        Exists? True	Is writable? True   (Size: 0)

JVM settings: Blitz-${index}                -Xmx621m -XX:MaxPermSize=512m -XX:+IgnoreUnrecognizedVMOptions
JVM settings: Indexer-${index}              -Xmx414m -XX:MaxPermSize=512m -XX:+IgnoreUnrecognizedVMOptions
JVM settings: PixelData-${index}            -Xmx621m -XX:MaxPermSize=512m -XX:+IgnoreUnrecognizedVMOptions
JVM settings: Repository-${index}           -Xmx414m -XX:MaxPermSize=512m -XX:+IgnoreUnrecognizedVMOptions

OMERO.web status... [RUNNING] (PID 1072)
Django version: 1.8.17

**Comment by atarkowska** [comment]
Did you see https://github.com/openmicroscopy/omero-test-daemon-c7-docker/blob/master/Dockerfile#L59 ?

You don't have to open Postgres port, just link Postgres container.

**Comment by joshmoore** [comment]
Other repos you might also want to look at:

 * https://github.com/openmicroscopy/omero-grid-docker
 * https://github.com/hadim/docker-omero

**Comment by heidricha** [comment]
to link postgres or use local server is all the same. it's not postgres what is new for me :)

none of the links above works out-of-the-box anyway.

**Comment by joshmoore** [comment]
Hi @heidricha:

> none of the links above works out-of-the-box anyway.

What do you mean?
~J

**Comment by heidricha** [comment]
Hi joshmoore!

I mean neither of the followings work to create a containerized omero instance:

- https://github.com/openmicroscopy/omero-test-daemon-c7-docker/blob/master/Dockerfile#L59
- https://github.com/openmicroscopy/omero-grid-docker
- https://github.com/hadim/docker-omero

All of them failes somewhere during image creation.

My Dockerfile build normally at the moment, but cannot start the service.

No one starts postgresql and nginx (it's a container, no init), I start them by hand.
If I start icegrid components, "omero admin start" complains about "Address already in use"
If I run "omero admin start" it looks like OK.

also can run web start, I can connect using a browser.

BUT: default web UI offers only omero:4064, and there's nothing listens on port 4064, su I just want to know:

- what service shall I start to have working service
- how to create users? I have found a doc, but it don't describe how to connect as admin...

**Comment by atarkowska** [comment]
Could you please be more specific how did you run them and what was exactly the error?

### omero-grid

Indeed omero-grid starts nginx on localhost:8080

```
$ docker run -d --name postgres -e POSTGRES_PASSWORD=postgres postgres
36b9dfa60f369b1a1a4bdb878e32265beddc065c0ca080358fed2c899d518864

$ docker run -d --name omero-master --link postgres:db -e DBUSER=postgres \
>     -e DBPASS=postgres -e DBNAME=postgres -p 4063:4063 -p 4064:4064 \
>     openmicroscopy/omero-grid master
Unable to find image 'openmicroscopy/omero-grid:latest' locally
latest: Pulling from openmicroscopy/omero-grid
785fe1d06b2d: Already exists 
da41ffd9b7fb: Pull complete 
7ccf2ad5f7d5: Pull complete 
51016c96e6ee: Pull complete 
1ce1479bb0c9: Pull complete 
5f8032eb2590: Pull complete 
b6214a41b9d7: Pull complete 
a427f7132547: Pull complete 
3aef7fca38d3: Pull complete 
b194e602f995: Pull complete 
7d6159a0c8e5: Pull complete 
Digest: sha256:d462fa09169372c535600c64fc79aa879e5bfd259e19658a463cd5e6106c58f1
Status: Downloaded newer image for openmicroscopy/omero-grid:latest
34fa3631014f48079a1e7d51c530970e4da6c99e23506f09b4a9e2d3fbfac91e

$ docker run -d --name omero-web --link omero-master:master -p 8080:8080 \
>     openmicroscopy/omero-grid-web
Unable to find image 'openmicroscopy/omero-grid-web:latest' locally
latest: Pulling from openmicroscopy/omero-grid-web
785fe1d06b2d: Already exists 
6cf67fba1c2b: Pull complete 
8d09c5cdcfc1: Pull complete 
38e70d37eb6f: Pull complete 
22a02aeec4c4: Pull complete 
0b2d78ecb572: Pull complete 
e946a077582f: Pull complete 
ba3f30df4a41: Pull complete 
1e869ff50342: Pull complete 
664359351d38: Pull complete 
Digest: sha256:29576f8c7f20044bd1326e81c5c13aae53ea575d051afc5a32a0bc9c7eaf09c8
Status: Downloaded newer image for openmicroscopy/omero-grid-web:latest
0491778d9cc9327381fd826abebe5b30cb6bccab393ef86b2a0d217ec42b851c

$ curl -I http://localhost:8080
HTTP/1.1 301 MOVED PERMANENTLY
Server: nginx/1.10.3
Date: Wed, 29 Mar 2017 15:21:02 GMT
Content-Type: text/html; charset=utf-8
Connection: keep-alive
Last-Modified: Wed, 29 Mar 2017 15:21:02 GMT
Expires: Wed, 29 Mar 2017 15:21:02 GMT
Location: http://localhost:8080/webclient/
Cache-Control: no-cache, no-store, must-revalidate, max-age=0
```

### omero-test
omero-test suitable for running CI tests, https://travis-ci.org/openmicroscopy/omero-test-daemon-c7-docker/jobs/216387719

**Comment by heidricha** [comment]
till this point it's ok, no error while starting. 
It's just about the same with mine, there are db, master, web... still cannot access the system.

Kinda out-of-topic here, but...

Tried to setup root user password (db-host: db, database: postgres, password: postgres.

Info from here:
https://www.openmicroscopy.org/site/support/omero5.3/sysadmins/unix/server-installation.html

Db looks like OK with a few warnings:
[omero@1280f10cf431 ~]$ psql -h db -U postgres postgres
Password for user postgres: 
psql (9.4.11, server 9.6.2)
WARNING: psql major version 9.4, server major version 9.6.
         Some psql features might not work.

postgres=# \d
 public | _fs_deletelog                                    | table    | postgres
 public | _lock_ids                                        | table    | postgres
 public | _lock_seq                                        | sequence | postgres
 public | _updated_annotations                             | table    | postgres
 public | acquisitionmode                                  | table    | postgres
 public | annotation                                       | table    | postgres
 public | annotation_mapvalue                              | table    | postgres
 public | annotationannotationlink                         | table    | postgres
 public | arc                                              | table    | postgres
 public | arctype                                          | table    | postgres
...
```

[omero@1280f10cf431 OMERO.server]$ bin/omero db script --password 'P@ssw0rD'
Using OMERO5.2 for version
Using 0 for patch
Using password from commandline
Saving to /home/omero/OMERO.server-5.2.7-ice36-b40/OMERO5.2__0.sql

[omero@1280f10cf431 OMERO.server]$ psql -h db -U postgres postgres < /home/omero/OMERO.server-5.2.7-ice36-b40/OMERO5.2__0.sql 
BEGIN
CREATE FUNCTION
CREATE FUNCTION
 assert_db_server_prerequisites 
--------------------------------
 
(1 row)

DROP FUNCTION
DROP FUNCTION
ERROR:  type "nonnegative_int" already exists
ERROR:  current transaction is aborted, commands ignored until end of transaction block


....
ERROR:  current transaction is aborted, commands ignored until end of transaction block
ERROR:  current transaction is aborted, commands ignored until end of transaction block
ERROR:  current transaction is aborted, commands ignored until end of transaction block
ERROR:  current transaction is aborted, commands ignored until end of transaction block
ROLLBACK


```

**Comment by heidricha** [comment]
hmmm... looks like there's no use recreating the whole database. updating only the root password helped a lot:
[omero@5fb7169a3a61 OMERO.server]$ bin/omero login
Server: [localhost:4064]localhost
Username: [omero]root
Password:
Created session 13e58c73-b198-40af-bbe6-066d6ea32f65 (root@localhost:4064). Idle timeout: 10 min. Current group: system
[omero@5fb7169a3a61 OMERO.server]$ 

Still cannot login on the web interface. Same root/pass doesn't work.

**Comment by heidricha** [comment]
login is OK locally, but web login is still refused.

web container can access master (port 4064).

[omero@5fb7169a3a61 OMERO.server]$ bin/omero login
Previously logged in to localhost:4064 as root
Server: [localhost:4064] 172.17.0.6
Username: [root]
Password:
Created session ecb6c113-82f3-48c0-bf8c-190c53a5641a (root@localhost:4064). Idle timeout: 10 min. Current group: system

**Comment by heidricha** [comment]
Message is: Error: Server is not responding, please contact administrator.

This is't true anyway, following the network traffic shows conversation between web and master on masters tcp port 4064.

**Comment by joshmoore** [comment]
@heidricha : What's the status of this thread? Should we close it and continue on https://github.com/openmicroscopy/omero-grid-docker/issues/3 ? Or are there things here you'd still like to see addressed?

**Comment by heidricha** [comment]
With your fork of omero-grid-docker it works! Thanks a lot!
