### ISSUE TITLE
Ice 3.7

### ISSUE THREAD

**Issue by dominikl** [ome/omero-install#214]
Review if Ice 3.7 is installed if installed via generic `apt-get -y install zeroc-ice-all-runtime` call.
/cc @jburel

**Comment by dominikl** [comment]
Debian 9 is ok, default Ice version is 3.6.3. But Debian 10 comes with 3.7 only (so does Ubuntu newer than 16.04)

**Comment by jburel** [comment]
For debian10 we use https://github.com/ome/zeroc-ice-debian10
