### ISSUE TITLE
Debian10 installation scripts fail

### ISSUE THREAD

**Issue by dominikl** [ome/omero-install#253]
It looks like postgres 11 isn't included in debian 10 any longer. You'd have to get it from postgres directly. Same what's been done for pg12: https://github.com/ome/omero-install/blob/develop/linux/step01_debian10_pg_deps.sh#L16 .

But after that, I failed at https://github.com/ome/omero-install/blob/a2d7b36cddd8995355a96f3fa6f7472f4cb72392/linux/step01_debian10_ice_venv.sh#L11 with `ERROR: zeroc_ice-3.6.5-cp37-cp37m-linux_x86_64.whl is not a supported wheel on this platform.`

**Comment by jburel** [comment]
I built the Debian10 docker image
i.e. ``./docker-build.sh debian10`` and everything works as expected.
I was able to connect to the server

**Comment by dominikl** [comment]
Maybe the docker image is older. It does not work on an installation from latest installation iso from https://www.debian.org/distrib/netinst .

**Comment by jburel** [comment]
``FROM debian:buster``

**Comment by dominikl** [comment]
Somehow the docker image seems to be different from the netinst installation. Anyway I can close the issue again, if it works with the docker image and that's sufficient.

**Comment by jburel** [comment]
It could be that netinst installation actually installs debian11 
pg-11 does not exist in that case.

**Comment by dominikl** [comment]
Argh, of course, the latest Debian is 11. Sorry. Closing the issue.
