### ISSUE TITLE
Minor autogenerate.sh issue

### ISSUE THREAD

**Issue by dominikl** [ome/omero-install#294]
While reviewing PR I noticed in the "Build walkthroughs" step:
```
Run cd linux
ubuntu2004
sed: can't read ./step01_ubuntu1804_deps.sh: No such file or directory
ubuntu2204
sed: can't read ./step01_ubuntu1804_deps.sh: No such file or directory
rocky9
```

I think that's caused by: https://github.com/ome/omero-install/blob/develop/linux/autogenerate.sh#L80 (respectively subsequentely: https://github.com/ome/omero-install/blob/develop/linux/autogenerate.sh#L91 ).
Should probably check the autogenerate script properly and remove any old ubuntu1804 bits.

**Comment by jburel** [comment]
Fixed in https://github.com/ome/omero-install/pull/291
