### ISSUE TITLE
Number scripts

### ISSUE THREAD

**Issue by joshmoore** [ome/omero-install#46]
In order to have a sysadmin make use of the scripts, having them number may be beneficial:

 * `01_setup.sh`
 * `02_postgres.sh`
 * etc.

cc: @sbesson @jburel @pwalczysko

**Comment by manics** [comment]
Is #45 https://github.com/manics/omero-install/commit/224d3a98ed8c3a789bfdad9b159cb28b2fca5d5e good enough?

**Comment by joshmoore** [comment]
Certainly better. But replacing the `setup_` names with a counting digit
might significantly increase readability.

**Comment by ximenesuk** [comment]
I don't fully follow your naming suggestion @joshmoore. At the moment we have `setup_blah`. In your example you seem to replacing the `setup` bit for some scripts and the `blah` bit for others?

**Comment by joshmoore** [comment]
@ximenesuk : guess I mostly mean, for any set of scripts, it would be good if a glob would pick things in the right order, something like:

```
dependencies-centos6.sh              --->  01_centos6_deps.sh
dependencies-centos7.sh              --->  01_centos7_deps.sh
dependencies-ubuntu1404.sh           --->  01_ubuntu1404_deps.sh
install-centos7.sh                   --->  install_centos7.sh (or just centos7.sh)
install.sh                           --->  centos6.sh
setup_apache_centos6.sh              --->  05_centos6_apache.sh
setup_centos6_selinux.sh             --->  ???
setup_cron.sh                        --->  ???
setup_nginx_centos6.sh               --->  05_centos6_nginx.sh
setup_nginx_centos7.sh               --->  05_centos7_nginx.sh
setup_nginx_ubuntu1404.sh            --->  05_ubuntu1404_nginx.sh
setup_omero.sh                       --->  04_all_omero.sh
setup_omero_apache.sh                --->  05_centos6_apache.sh
setup_omero_daemon_centos6.sh        --->  06_centos6_daemon.sh
setup_omero_daemon_centos7.sh        --->  06_centos7_daemon.sh
setup_omero_daemon_noweb_centos6.sh  --->  06_centos6_daemon_no_web.sh
setup_omero_daemon_ubuntu1404.sh     --->  06_ubuntu1404_daemon.sh
setup_omerodev.sh                    --->  04_all_omerodev.sh
setup_permissions.sh                 --->  ???
setup_postgres.sh                    --->  03_all_postgres.sh
system_setup.sh                      --->  02_all_setup.sh

```

**Comment by ximenesuk** [comment]
Thanks  @joshmoore that makes it clearer. Given the nested structure of some of these script calls does that work cleanly? (Not that I have any better suggestions.)

**Comment by jburel** [comment]
I will add the prefix ```step``` to make it even more obvious
and probably keep ```install``` (```deploy-on?```) and the parameter we specify for the install script:
webserver branch

**Comment by ximenesuk** [comment]
Unless there is good reason I will rename
```
setup_permissions.sh                 --->  step07_all_perms.sh
setup_cron.sh                        --->  step08_all_cron.sh
```
to be consistent with other non-OS-specific scripts.

**Comment by joshmoore** [comment]
No objections from me.

**Comment by ximenesuk** [comment]
@joshmoore, @jburel a few questions and comments:

```
install-centos6py27-apache.sh --> install_centos6_py27_apache24.sh
install-centos6py27.sh        --> install_centos6_py27_nginx.sh
```
makes sense  though this means in most script names the Python version is not explicitly stated, but that seems okay. Also, adding nginx makes sense to me even if it is the default.

We have a few additional scripts that fall outwith the current numbering, sort of half steps!

```
setup_centos6_selinux.sh --> ???
```
This falls between steps 5 and 6 for centos 6 set-up. Should it be rolled into step 5 or do we need it as an extra step?

```
dependencies-ice-centos6py27.sh
```
This is only on centos 6, python 2.7. Again, should it be rolled into the dependencies, step 1?

```
user_setup_centos6py27.sh
```
This is also centos 6, python 2.7. It follows step 2 which is an `_all_` step.  Given it is just:
```
echo source \~omero/omero-centos6py27.env >> ~omero/.bashrc
```
this one could be removed as a script and added directly to the relevant install scripts.

Finally, some scripts with not have steps missing. Is this a problem - should there be noop steps? - or not?

**Comment by joshmoore** [comment]
* explict nginx, etc -- works for me to be explicit everywhere.
 * setup_centos6_selinux.sh -- I'd say merge into the parent
 * `*centos6py27*` -- I'd say merge as well. @manics may have been planning something, but we can review that when the time comes. (Note: one issue may be the layout of the docs)
 * missing steps -- do you have a list?

**Comment by jburel** [comment]
for centos6 I will merge, since that will be one of the options mentioned in a previous comment

**Comment by jburel** [comment]
By missing steps do you mean starting up web and server?

**Comment by ximenesuk** [comment]
@joshmoore the centos7 scripts omit steps 7 and 8.

**Comment by jburel** [comment]
with the merge of centos6python, we will probably also need the ability to specify the python version as a parameter

**Comment by ximenesuk** [comment]
I have a branch at https://github.com/ximenesuk/omero-install/tree/script-rename which is based on a local merge so not suitable for a PR as yet. Once any outstanding PRs are in I can rebase this and open a PR. There are also a few loose ends that I need to pick up.

**Comment by joshmoore** [comment]
Closing this in favor of @ximenesuk's upcoming PR.
