### ISSUE TITLE
Ubuntu 12.04 v Postgresql 9.2+

### ISSUE THREAD

**Issue by joshmoore** [ome/omero-install#84]
@carandraug pointed out on #ome:

> The docs said that 5.1 supported Ubuntu 12.04 but I found that it didn't because it required postgresql 9.2. I guess technically it is supported since I can always build it from source myself.

We should double-check that what's documented as supported is represented in this repo to prevent anything from slipping through the cracks.

**Comment by carandraug** [comment]
Here's the [relevant page](http://www.openmicroscopy.org/site/support/omero5.1/sysadmins/version-requirements.html) of the docs:

> [...]
> - Linux (Ubuntu LTS)
>   - [5.1] 10.04 dropped, 12.04 deprecated, 14.04 recommended
> 
> [...]
> - PostgreSQL
>   - [5.1] 8.4/9.0/9.1 dropped, 9.2 deprecated, 9.3+ recommended

However, Ubuntu 12.04 (precise) [only has postgreSQL 9.1](http://packages.ubuntu.com/precise/postgresql) which omero 5.1 does not support.

**Comment by joshmoore** [comment]
@jburel: worth reviewing for 5.3?

**Comment by jburel** [comment]
We have improved the requirements page for 5.3.0 
This issue can be closed
